use_frameworks!

target 'ChartView_Example' do
  pod 'ChartView', :path => '../'

  target 'ChartView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
